on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: [master]

name: Test on Linux
jobs:
  test-linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake libx11-dev libxtst-dev"

      - name: Install Catch2
        run: |
          git clone https://github.com/catchorg/Catch2.git 
          cd Catch2
          git checkout v2.13.7
          cmake -Bbuild -H. -DBUILD_TESTING=OFF -DCATCH_BUILD_EXAMPLES=OFF -DCATCH_BUILD_STATIC_LIBRARY=ON
          sudo cmake --build build/ --target install

      - name: Compile
        run: "mkdir build && cd build && cmake .. -DLIME_BUILD_TESTS=ON -DLIME_IS_CI=ON && cmake --build . --config Debug"

      - name: Run Tests
        run: "./build/tests"