on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: [master]

name: Test on Linux
jobs:
  test-linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake libx11-dev libxtst-dev"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -DLIME_BUILD_TESTS=ON -DLIME_IS_CI=ON && cmake --build . --config Debug"

      - name: Run Tests
        run: "./build/tests"