on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: [master]

name: Test on Windows
jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive

      - name: Install Catch2
        run: |
          git clone https://github.com/catchorg/Catch2.git 
          cd Catch2
          git checkout v2.13.7
          mkdir build
          cd build
          cmake .. -DBUILD_TESTING=OFF -DCATCH_BUILD_EXAMPLES=OFF -DCATCH_BUILD_STATIC_LIBRARY=ON
          cmake --build . --target install

      - name: Compile
        run: "mkdir build && cd build && cmake .. -DLIME_BUILD_TESTS=ON && cmake --build . --config Debug"

      - name: Run Tests
        run: "D:\\a\\lime\\lime\\build\\Debug\\tests.exe" # Hardcoded path because windows is cancerous.